
[General]
	#Add Only Silver items to chest loot?
	AddModLootToChests = true
	#Can build silver golems?
	BuildSilverGolem = true

[Enchantments]
	#Everlasting Enchantment enabled?
	EnableSilverAura = true
	#Enable Incantation enchantment?
	EnableIncantation = true

